units:
  kx: cx
  ky: cy
  padding: 3
  px: kx + padding
  py: ky + padding
  fillet: 3
  choc_cutout: 13.8

  mcu_x: 18
  mcu_y: 38
  mcu_p: 2

  $default_width: cx
  $default_height: cy
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
        tags: [1u]
      rotate: 10
      columns:
        outer:
          key:
          rows.mod.skip: true
        pinky:
          key:
          rows.mod.skip: true
        ring:
          key:
            stagger: 12
            splay: -5
          rows.mod.skip: true
        middle:
          key:
            stagger: 5
            splay: -5
        index:
          key:
            stagger: -5
          rows.mod.skip: true
        inner:
          key:
            stagger: -2.5
          rows.mod.skip: true
        inner_far:
          key:
            stagger: -2.5
            skip: true
          rows:
            bottom.skip: false
      rows:
        mod:
        bottom:
        home:
        top:
        num:
    thumb:
      key:
        padding: 1ky
        spread: 1kx
        shift: [6, -6]
      anchor:
        ref: matrix_index_mod
      columns:
        alt:
          key:
            splay: -15
            tags: [1u]
        inner:
          key:
            splay: -15
            rotate: 90
            spread: 1.5kx
            tags: [15u]
        outer:
          key:
            splay: -10
            rotate: 90
            spread: 1.25kx
            shift: [5, -7]
            tags: [15u]
      rows:
        mod:
outlines:
  _switches:
    - what: rectangle
      where: true
      size: choc_cutout
      bound: false
  _switch_plate:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_num
          shift: [0, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: matrix_index_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_far_bottom
          shift: [-0.5px + padding, 0.5py]
        - ref: matrix_inner_far_bottom
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_far_bottom
          shift: [0.5px, -0.5py]
        - ref: thumb_outer_mod
          shift: [0.75py, -0.5px]
        - ref: thumb_outer_mod
          shift: [-0.75py, -0.5px]
        - ref: matrix_outer_bottom
          shift: [-0.5px, -0.5py]
    - what: circle
      radius: 144
      where:
        ref: matrix_middle_mod
        shift: [-31, -160]
      operation: subtract
  plate: 
    - name: _switch_plate
      fillet: fillet
    - name: _switches
      operation: subtract
  _keycaps1u:
    - what: rectangle
      where: /1u/
      size: [kx-0.5, ky-0.5]
  _keycaps15u:
    - what: rectangle
      where: /15u/
      size: [1.5kx-0.5, 1ky-0.5]
  _all_keycaps: [+_keycaps1u, +_keycaps15u]
  plate_with_keycaps: [+plate, -_all_keycaps]
  _mcu:
    - what: rectangle
      size: [mcu_x, mcu_y]
      where:
        ref: matrix_inner_num
      adjust:
        shift: [0.5px + 0.5mcu_x + mcu_p, 0.5py - 0.5mcu_y - 0.5]
  board:
    - name: _switch_plate
    - what: polygon
      operation: add
      points:
        - ref: matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_num
          shift: [0.5px + mcu_x + 2mcu_p, 0.5py]
        - ref: thumb_outer_mod
          shift: [0.75py, -0.5px]
        - ref: matrix_inner_far_bottom
          shift: [-0.5px, -0.5py]
  board_with_components:
    [+board, -_all_keycaps, -_mcu]
pcbs:
  qapla:
    template: kicad8
    outlines:
      main:
        outline: board
      keycaps:
        outline: _all_keycaps
        layer: Eco1.User
