units:
  kx: u
  ky: u
  padding: 3
  px: kx + padding
  py: ky + padding
  fillet: 2
  mx_cutout: 14

  mcu_x: 18
  mcu_y: 35
  mcu_p: 1.5
  padding_outside_mcu: 8.5

  wall_thickness: 2

  $default_width: u
  $default_height: u
points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -150]
      key:
        padding: 1ky
        spread: 1kx
        tags: [1u, key]
      rotate: 10
      columns:
        outer:
          key:
            column_net: P20
          rows.mod.skip: true
        pinky:
          key:
            column_net: P19
          rows.mod.skip: true
        ring:
          key:
            stagger: 12
            splay: -5
            column_net: P18
          rows.mod.skip: true
        middle:
          key:
            stagger: 5
            splay: -5
            column_net: P15
        index:
          key:
            stagger: -5
            column_net: P14
          rows.mod.skip: true
        inner:
          key:
            stagger: -2.5
            column_net: P16
          rows.mod.skip: true
        inner_far:
          key:
            stagger: -2.5
            skip: true
            column_net: P10
          rows:
            bottom.skip: false
      rows:
        mod:
          row_net: P5
        bottom:
          row_net: P6
        home:
          row_net: P7
        top:
          row_net: P8
        num:
          row_net: P9
    thumb:
      key:
        padding: 1ky
        spread: 1kx
        shift: [6, -6]
      anchor:
        ref: matrix_index_mod
      columns:
        alt:
          key:
            splay: -15
            tags: [1u, key]
            column_net: P14
        inner:
          key:
            splay: -15
            rotate: 90
            spread: 1.5kx
            tags: [15u, key]
            column_net: P16
        outer:
          key:
            splay: -10
            rotate: 90
            spread: 1.25kx
            shift: [5, -7]
            tags: [15u, key]
            column_net: P10
      rows:
        mod:
          row_net: P5
    mount_points:
      anchor:
        shift: [100, -150]
      key:
        height: 2
        width: 2
        tags: [hole]
      columns:
        hole1:
          key:
            shift: [2kx, 6ky]
        hole2:
          key:
            shift: [2.15kx, 2.2ky]
        hole3:
          key:
            shift: [3.85kx, 6.65ky]
        hole4:
          key:
            shift: [3.1kx, 2.25ky]
        hole5:
          key:
            shift: [3.8kx, 2.8ky]
outlines:
  _switches:
    - what: rectangle
      where: /key/
      size: mx_cutout
      bound: false
  _switch_plate:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [1.5px, 0.5py]
        - ref: matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_far_bottom
          shift: [-0.5px + padding, 0.5py]
        - ref: matrix_inner_far_bottom
          shift: [mcu_x + 2mcu_p + padding_outside_mcu + padding - 0.5px, 0.5py]
        - ref: matrix_inner_far_bottom
          shift: [mcu_x + 2mcu_p + padding_outside_mcu + padding - 0.5px, -0.5py]
        - ref: thumb_outer_mod
          shift: [0.75ky + 0.5padding, -0.5px]
        - ref: thumb_outer_mod
          shift: [-0.75ky - 0.5padding, -0.5px]
        - ref: matrix_outer_bottom
          shift: [-0.5px, -0.5py]
    - what: circle
      radius: 203.5
      where:
        ref: matrix_middle_mod
        shift: [-46, -221]
      operation: subtract
  plate:
    - name: _switch_plate
      fillet: fillet
    - name: _switches
      operation: subtract
  _keycaps1u:
    - what: rectangle
      where: /1u/
      size: [kx-0.5, ky-0.5]
  _keycaps15u:
    - what: rectangle
      where: /15u/
      size: [1.5kx-0.5, 1ky-0.5]
  _all_keycaps: [+_keycaps1u, +_keycaps15u]
  _mcu:
    - what: rectangle
      size: [mcu_x, mcu_y]
      where:
        ref: matrix_inner_num
      adjust:
        shift: [0.5px + 0.5mcu_x + mcu_p, 0.5py - 0.5mcu_y - 0.5]
  _pcb_outline:
    - name: _switch_plate
    - what: polygon
      operation: add
      points:
        - ref: matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_num
          shift: [0.5px + mcu_x + 2mcu_p + padding_outside_mcu, 0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px + mcu_x + 2mcu_p + padding_outside_mcu, -0.5py]
        - ref: matrix_inner_far_bottom
          shift: [-0.5px, -0.5py]
  pcb:
    - name: _pcb_outline
      fillet: fillet
    - what: rectangle
      operation: subtract
      size: [7, 2]
      where:
        - ref: matrix_inner_num
          shift: [0.5px + mcu_x + 2mcu_p + padding_outside_mcu, -0.5py - 0.5]
  _tilt_handle:
    - what: polygon
      points:
      - shift: [0, 0]
      - shift: [3.5, -2]
      - shift: [0, -3.9]
      - shift: [-3.5, -2]
      operation: stack
    - what: circle
      radius: 2.3
      where.shift: [2.3, -4]
      operation: add
    - what: circle
      radius: 1.55
      where.shift: [2.3, -4]
      operation: subtract
  bottom_case_outer:
    - name: _pcb_outline
      fillet: fillet
    - name: _tilt_handle
      where:
        ref: matrix_inner_num
        shift: [0.5px + mcu_x+ 2mcu_p + padding_outside_mcu, 0.45ky]
    - name: _tilt_handle
      where:
        ref: matrix_inner_bottom
        shift: [0.5px + mcu_x+ 2mcu_p + padding_outside_mcu, -0.5ky]
    - name: _tilt_handle
      where:
        ref: matrix_outer_num
        shift: [-0.5px, 0]
      adjust:
        rotate: 180
    - name: _tilt_handle
      where:
        ref: matrix_outer_bottom
        shift: [-0.5px, -0.5ky + fillet]
      adjust:
        rotate: 180
  bottom_case_inner:
    - name: _pcb_outline
      expand: -wall_thickness
      fillet: fillet
  mount_standoffs:
    - what: circle
      where: /hole/
      radius: 2.3
  mount_holes:
    - what: circle
      where: /hole/
      radius: 1.55
  oled_cover_plate:
    - what: rectangle
      size: [28.95, 59]
      fillet: fillet
    - what: circle
      radius: 1.55
      operation: subtract
      adjust:
        shift: [28.95/2 - 3, 59/2 - 3]
    - what: circle
      radius: 1.55
      operation: subtract
      adjust:
        shift: [-28.95/2 + 3, 59/2 - 3]
pcbs:
  qapla_mx:
    template: kicad8
    outlines:
      main:
        outline: pcb
      keycaps:
        outline: _all_keycaps
        layer: Eco1.User
    footprints:
      mx:
        what: ceoloide/switch_mx
        where: /key/
        params:
          reversible: true
          hotswap: true
          solder: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode-bottom:
        what: ceoloide/diode_tht_sod123
        where: /(num|home)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          reversible: true
          include_tht: false
        adjust:
          shift: [7.5 , -0.5ky + 1.2]
          rotate: 180
      diode-top:
        what: ceoloide/diode_tht_sod123
        where: /(top|bottom|mod)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          reversible: true
          include_tht: false
        adjust:
          shift: [7.5 , 0.5ky - 1.2]
          rotate: 180
      via_pad_1:
        what: via
        where: key
        adjust:
          shift: [0, 8]
        params:
          net: "{{column_net}}"
      via_pad_2:
        what: via
        where: /(num|home)/
        adjust:
          shift: [0, 7]
        params:
          net: "{{colrow}}"
      promicro:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_inner_num
          shift: [0.5px + 0.5mcu_x + mcu_p, 0.5py - 0.5mcu_y - 0.5]
        params:
          reversible: true
      display:
        what: ceoloide/display_nice_view
        where:
          ref: matrix_inner_num
          shift: [0.5px + 0.5mcu_x + mcu_p, -0.5ky - mcu_p - 0.25]
        params:
          reversible: true
          include_traces: false
          MOSI: P2
          SCK: P3
          CS: P1
      reset-switch:
        what: reset_switch
        where:
          ref: matrix_inner_top
          shift: [0.5px + mcu_x + mcu_p + 6, 0]
          rotate: 90
      power_switch:
        what: switch_JS102011SAQN
        where:
          ref: matrix_inner_num
          shift: [0.5px + mcu_x + 2mcu_p + 3.25, 0.5py - 2.5]
          rotate: 180
        params:
          reversible: true
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          reversible: true
        where:
          ref: matrix_inner_num
          shift: [0.5px + mcu_x + 2mcu_p + 3.25, 1]
      battery_led:
        what: resistor_led_0805_2012Metric
        where:
          ref: matrix_inner_num
          shift: [0.5px + 0.5mcu_x + mcu_p, -0.5ky - mcu_p - 19.8]
        params:
          GPIO: P4
      display_cover_hole_1:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_inner_far_bottom
          shift: [-4, 14]
      display_cover_hole_2:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_inner_far_bottom
          shift: [18.5, 14]
      mounting_holes:
        what: ceoloide/mounting_hole_plated
        where: /hole/
        params:
          drill: 4.8
          outline: 0.2
  qapla_plate_mx:
    template: kicad8
    outlines:
      main:
        outline: plate
    footprints:
      mounting_holes:
        what: ceoloide/mounting_hole_plated
        where: /hole/
        params:
          drill: 2.2
          outline: 1.2
cases:
  bottom:
    - name: bottom_case_outer
      extrude: 1
  bottom_inner:
    - name: bottom_case_inner
      extrude: 1
  _outer_wall:
    - name: bottom_case_outer
      extrude: 3
  _inner_wall:
    - name: bottom_case_inner
      extrude: 3
  mount_standoffs:
    - name: mount_standoffs
      extrude: 6
  mount_holes:
    - name: mount_holes
      extrude: 4
      shift: [0, 0, 2]
  wall:
    - what: case
      name: _outer_wall
      operation: add
    - what: case
      name: _inner_wall
      operation: subtract
  case:
    - what: case
      name: bottom
      operation: add
    - what: case
      name: wall
      operation: add
    - what: case
      name: mount_standoffs
      operation: add
    - what: case
      name: mount_holes
      operation: subtract
  oled_cover_plate:
    - name: oled_cover_plate
      extrude: 3